### ISSUE TITLE
Update bootstrap, jquery, angular to latest version.

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#103]
Updating to the latest version will resolve a few touch device compatibility issues (namely the popovers not working on ipad (fixed in 2.2.2), and potentially some positioning overflow issues).

Chris, do you see a problem with updating? (I looked over the change notes and I don't think they will impact us.  Git says that we haven't altered any of the bootstrap.css as well)  

If we're good to update, I will update it after the ui-fixes land today.  jQuery will get bumped to 1.9 as well (2.0 might introduce compatibility issues with old IE).  Angular to 1.0.6 will pick up some directive fixes, firefox CORS, and date parsing fix.

**Comment by chris-wood** [comment]
I don't see any problems with this. Even still, I wouldn't take the risk.

**Comment by rpk7524** [comment]
Closed in cee2303.
