### ISSUE TITLE
UI feature to differentiate public/private messages

### ISSUE THREAD

**Issue by dge9788** [ithunt/asksg#18]

**Comment by ithunt** [comment]
Added a privateMessage boolean to Message object. May be moved to Conversation before master merge

**Comment by dge9788** [comment]
Usability testing identified this as a needed enhancement, raising priority.

**Comment by rpk7524** [comment]
Implementation discussion: move configuration and users config page to a separate config page. When admin logs in, to the left of the logout area, insert a link to the configuration page.  Hide with angular directives on user role.  For delete conversation option wrap with a similar directive.  Protect the configuration Apis with spring security, as well as the delete conversation API.  On configuration page, link back to dashboard in the same place as link to config page.

**Comment by rpk7524** [comment]
Comment above was supposed to be on another issue.  Implementation discussed with sponsor is to create service icons that have the text 'private' underneath them, and on private conversations use that icon instead of the standard one.

**Comment by dge9788** [comment]
Closed with commit 749706b merged to master.
