### ISSUE TITLE
Configuration and User pages are available to all Roles

### ISSUE THREAD

**Issue by ithunt** [ithunt/asksg#28]
Any user with any role can access the configuration and user pages. Should only be accessible by Admin
UI - hide
backend - restrict service calls

**Comment by ithunt** [comment]
Deny access to the Urls in the background and then hide the tabs for users who do not have access

**Comment by rpk7524** [comment]
Implementation discussion: move configuration and users config page to a separate config page. When admin logs in, to the left of the logout area, insert a link to the configuration page. Hide with angular directives on user role. For delete conversation option wrap with a similar directive. Protect the configuration Apis with spring security, as well as the delete conversation API. On configuration page, link back to dashboard in the same place as link to config page.

**Comment by dge9788** [comment]
The UI portion of this bug is Issue #44

**Comment by ithunt** [comment]
To fix the backend part of this bug: Injecting principal into the conversations controller and nulling from there should be sufficient. Deferred until Ryan's pagination code is set
