### ISSUE TITLE
Facebook posts are not always ordered right

### ISSUE THREAD

**Issue by dge9788** [ithunt/asksg#37]
Specifically, sometimes the first message displayed in the conversation is not the original post and is instead one of the comments on the post.

**Comment by rpk7524** [comment]
Possibly fixed in my order_by_conversation branch - messages should be ordered now in json (since we changed messages to a list, and have the orderby annotation on them).  Removed bad orderby filter in ui for messages.  Still need to make sure created is set correctly for each incoming message.

**Comment by rpk7524** [comment]
Resolved in 85f4d42.
