### ISSUE TITLE
Email does not support conversations

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#47]
When an external user replies to a response from a senator, the incoming email will not be affiliated with the existing conversation.

Explore some primitive mechanism to attach the new message to the existing conversation (by external user / subject / by time).  Even if we attach all of the same From external user to the same conversation for the duration of their 4 years here, it would be better to group them than not.  Ideally we would check by subject reply, but that is more difficult (what is the subject is changed slightly, or email clients add multiple Re: Re: Re: prefixes - might be possible to see if maven has a fuzzy match lib we can pull, or otherwise we can do contains for each word in the subject against that users past conversations with the same subject).  Another approach would be to check if the message is within a certain time period (date match within the last month).

**Comment by ithunt** [comment]
This can also be implemented like twilio per anthonys suggestion. Same person, less than a week since last message, add. Otherwise new conversation.

**Comment by dge9788** [comment]
Rolled into Issue #105.
