### ISSUE TITLE
TwilioConfig cannot autowire providerconfig, need to specify qualifier annotation

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#5]
Please use @Qualifier("id") when autowiring shared components.

**Comment by dge9788** [comment]
i added @Qualifier("twilioConfig") to the (i believe) right place in Twilio.java and added the <qualifier .../> to the providers XML. should be fixed, can you verify?

**Comment by rpk7524** [comment]
LG, you can close.  Only had to add annotation in the code, but specifying the type in the xml doesn't hurt anything.
