### ISSUE TITLE
Service Login information is exposed to asksg users

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#52]
The service api is shared between the dashboard and service configuration views.  In order to send less information to the dashboard (omit the login information), we need to implement a mechanism to omit this information (additional (unguarded) service endpoints that support serialization from a viewmodel that is constructed from the full service model).

**Comment by ithunt** [comment]
If user is not an admin, clear the serialized fields by overriding serializer. Need to assure this doesn't break calls on the return trip
