### ISSUE TITLE
Conversation does not have a subject field

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#62]
Conversations need a subject field added.  This should be populated by:
Twitter - Message[0]
Facebook - Message [0] snippet 
Email - Subject property
Twilio - Message[0]
Reddit - Submission Title

The ui then needs to bind to the subject field when creating the conversation object, and then use {{convo.subject}} instead of message[0] in the dashboard html.

**Comment by dge9788** [comment]
Merged to master with commit 434c75d.
