### ISSUE TITLE
Dashboard conversations view has both reply button and Submit button 

### ISSUE THREAD

**Issue by dge9788** [ithunt/asksg#73]
First round usability testing identified the two buttons (especially since Reply doesn't do much anymore) as confusing.

**Comment by dge9788** [comment]
Fixed with commit f515dda (just in time for usability testing).

**Comment by rpk7524** [comment]
Is the javascript function called by the ui (showResponseForm) used anywhere else?  If not, it should be removed as well.

**Comment by dge9788** [comment]
Closed with commit 925bdc9.
